### ISSUE TITLE
Doesn't work with colemak

### ISSUE THREAD

**Issue by teackot** [iberianpig/fusuma-plugin-sendkey#35]
Hi! I recently switched to the colemak layout, however, the `sendkey: "LEFTCTRL+R"` command sends `Ctrl-P` instead of `Ctrl-R`

**Comment by iberianpig** [comment]
It seems that when you execute the `sendkey: "LEFTCTRL+R"` command, it sends `Ctrl-P` instead. This is because Sendkey itself is sending at the evdev layer, which operates at a level lower than X11 or Wayland.

Below is a comparison table of the QWERTY and Colemak layouts:

|       QWERTY                  |      COLEMAK                 |
|:------------------------------:|:----------------------------:|
|   Q W E R T Y U I O P        |    Q W F P G J L U Y ;      |
|   A S D F G H J K L          |    A R S T D H N E I O     |
|         Z X C V B N M         |     Z X C V B K M , . /     |

First, please run `libinput debug-events --show-keycodes` to check which key code the key you pressed is mapped to. By identifying the correct key code and then reconfiguring Sendkey based on that, you may be able to resolve the issue.

**Comment by teackot** [comment]
I see, guess I'll just have to replace the keys with the corresponding QWERTY keys. Good thing I only need to replace one

Thank you!
